### ISSUE TITLE
falsche Berechnung der Monate beim Flugmodus

### ISSUE THREAD

**Issue by sepplsche** [sepplsche/skrupel#1]
Nachdem ich das mit dem Warpbonus eingebaut habe, funktioniert in der Gelaxy-Ansicht beim Flugmodus eines Schiffes die Berechnung der Monate nicht mehr korrekt. Ausgeführt wird der Flug mit der richtigen Anzahl Lichtjahre. Aktueller Warpbonus im Master ist 1. Also die Lichtjahre die zurückgelegt werden sind: ($warp + 1) * ($warp + 1).

**Comment by sepplsche** [comment]
warpstufen angepasst:
1+0: Sonnensegel (ab und zu 81 LJ)
2+3: Tarnung = 25 LJ
3+3: Enttarnung = 36 LJ
4+2: weniger Verbrauch = 36 LJ
5+1: Signaturmaskierung = 36 LJ
6+1: alternativer Treibstoff = 49 LJ
7+0: ab und zu keine Tarnung, höchster Antrieb mit Traktorstrahl = 49 LJ
8+1: kein Traktorstrahl = 81 LJ
9+2: kein Traktorstrahl und 1/2-Frachtraum = 121 LJ

neue warpstufen werden nur beim zugberechnen angewendet nicht aber in der galaxy/flotten ansicht

**Comment by hdiederichs** [comment]
Wieso wurden die Warpstufen angepasst? Was war falsch an den alten?

**Comment by sepplsche** [comment]
Wenn das Spiel mal ein paar Runden geht, so ab ca. 50, ist das Imperium / die sichtbare Karte recht gross und man ist rundenlang nur damit beschäftigt rumzufliegen. Idee war, dass es im späteren Spiel etwas schneller vorangeht. Deshalb hab ich mal ausprobiert die Warpstufen anzupassen. Das geht beim zugberechnen recht gut. Aber in der Galaxy-Ansicht im Flugmodus wird die Reststrecke falsch gerechnet.

Aktueller Stand: Beim zug berechnen werden die neuen werte genommen, in der Galaxy-Ansicht im Flugmodus werden die alten Werte angezeigt, siehe Issue-4.

Das Ganze ist in eigene Funktionen ausgelagert in der "inc.host_func.php" die Funktionen "strecke" und "bonus" und kann daher leicht angepasst/zurückgesetzt werden, falls das eine doofe Idee war.
